sudo: required
services:
 - docker

before_install:
  - docker build -t gopalgurram/docker-react -f Dockerfile.dev .

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-334754800619"
 bucket_path: "docker-react"
 on:
    branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_access_key: "$AWS_SECRET_KEY"
